modLoader="javafml"
loaderVersion="[37,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Api/issues"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-api"
